---
ignore:
  - "build"
  - "devel"
  - "test"

fixes:
  - "src/node_example/::"

codecov:
  require_ci_to_pass: yes
  token: 2506f753-75fa-49b9-a728-d42f267e8843


coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
